crave/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.home,name='home'),
    path('about/', views.about, name='about'),
    path('places/', views.places_index, name='index'),
    path('places/hitlist', views.hitlist_index, name='hitlist_index'),
    path('places/create/', views.PlaceCreate.as_view(),name='places_create'),
    path('places/<int:place_id>/add_photo/', views.add_photo, name='add_photo'),
    path('places/<int:place_id>/', views.places_detail, name='detail'),
    path('places/<int:pk>/update/', views.PlaceUpdate.as_view(),name='places_update'),
    path('places/<int:pk>/delete/', views.PlaceDelete.as_view(),name='places_delete'),
    path('accounts/signup/', views.signup, name='signup'),

]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

RATING=(
    (0,''),
    (1, '⭐️'),
    (2,'⭐️⭐️'),
    (3,'⭐️⭐️⭐️'),
    (4,'⭐️⭐️⭐️⭐️'),
    (5,'⭐️⭐️⭐️⭐️⭐️')
)


TYPES =(
  ('R','restaurant'),
  ('C','cafe'),
  ('B','bar'),
  ('D', 'dessert'),
)

STATUS = (
  ('B','Been'),
  ('H','Have not been'),
)
# Create your models here.

class Place(models.Model):
  name = models.CharField(max_length=100)
  location = models.CharField(max_length=100)
  status = models.CharField(
    max_length=1,
    choices=STATUS,
  )
  notes = models.TextField(
    max_length=2500,
    blank=True,
    )
  place_type = models.TextField(
    choices=TYPES,
  )
  rating = models.IntegerField(
    choices=RATING,
    default=0
    )
  user = models.ForeignKey(User, on_delete=models.CASCADE)
  
  def __str__(self):
    return f'{self.name} ({self.id})'

  def get_absolute_url(self):
    return reverse('detail', kwargs={'place_id': self.id})

class Photo(models.Model):
    url = models.CharField(max_length=200)
    place = models.ForeignKey(Place, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for place_id: {self.place_id} @{self.url}"

main_app/views.py
import uuid
import boto3
import os
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import ListView, DetailView
from django.contrib.auth import login
from .models import Place
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Place, Photo

# Create your views here.

def home(request):
  if request.user.is_authenticated:
    return redirect('index')
  else:
    return redirect('about')

def about(request):
  return render(request, 'about.html')

@login_required
def places_index(request):
  places = Place.objects.filter(user=request.user, status="B")
  return render(request, 'places/index.html', {
    'places': places
  })

@login_required
def places_detail(request, place_id):
    place = Place.objects.get(id=place_id)
    return render(request,'places/detail.html',{
        'place': place,
        'user': place.user
    })

@login_required
def hitlist_index(request):
  places = Place.objects.filter(user=request.user, status='H')
  return render(request, 'places/hitlist.html', {
    'places': places
  })

class PlaceCreate(LoginRequiredMixin, CreateView):
    model = Place
    fields = ['name', 'status', 'location', 'place_type', 'notes', 'rating']

    def form_valid(self, form):
     form.instance.user = self.request.user  
     return super().form_valid(form)

class PlaceUpdate(LoginRequiredMixin, UpdateView):
    model = Place
    fields = ['name', 'status', 'location', 'place_type', 'notes', 'rating']

class PlaceDelete(LoginRequiredMixin, DeleteView):
    model = Place
    success_url ='/places'

@login_required
def add_photo(request, place_id):
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
        try:
            bucket = os.environ['S3_BUCKET']
            s3.upload_fileobj(photo_file, bucket, key)
            url = f"{os.environ['S3_BASE_URL']}{bucket}/{key}"
            Photo.objects.create(url=url, place_id=place_id)
        except Exception as e:
            print('An error occurred uploading file to S3')
            print(e)
    return redirect('detail', place_id=place_id)

def signup(request):
  error_message = ''
  if request.method == 'POST':
    form = UserCreationForm(request.POST)
    if form.is_valid():
      user = form.save()
      login(request, user)
      return redirect('index')
    else:
      error_message = 'Invalid sign up - try again'
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)


    

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}
<h1>Meet <span style="color:#FFE24A">Crave</span></h1>


<p>
Welcome to Crave, the ultimate foodie app! Are you tired of trying to remember which restaurants you've been to and what dishes you loved? Crave is here to help! With our app, you can track all of your dining experiences, rate restaurants, and leave notes about your favorite dishes.

But wait, there's more! Crave also allows you to create a wishlist of all the restaurants you've been dying to try. Keep your foodie bucket list in one place and never forget about that new hot spot everyone's been talking about. You can even see which of your friends have tried the restaurants on your list, and ask for their recommendations.

Say goodbye to boring meals and hello to culinary adventures. Whether you're a foodie looking to try new restaurants, or just want to keep track of your favorite places, Crave has got you covered. Download now and start exploring the culinary world!
</p>
{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Crave</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDqlpeJtFbNQZVU9IhQJbYW4PIBPaDZuqY&libraries=places"></script>

</head>
<body>
    <header class="navbar-fixed">
        <nav>
            <div class="nav-wrapper">
                <ul>
                    <li><a href="{% url 'home' %}" class="left brand-logo">&nbsp;&nbsp;CRAVE</a></li>
                </ul>
                <ul class="right">
                    <li><a href="{% url 'about' %}" id="about-link">ABOUT</a></li>
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'places_create' %}" id = "create-link">ADD PLACE</a></li>
                    <li><a href="{% url 'index' %}" id="list-link">LIST</a></li>
                    <li><a href="{% url 'hitlist_index' %}" id="hitlist-link">HIT LIST</a></li>
                    <li><a href="{% url 'logout' %}">LOG OUT</a></li>
                    {% else %}
                    <li><a href="{% url 'signup' %}">SIGN UP</a></li>
                    <li><a href="{% url 'login' %}">LOG IN</a></li>
                    {% endif %}
                    
                </ul>
            </div>
        </nav>
    </header>
    <main class="container">
        {% block content %}
        {% endblock %}
    </main>
  	<footer class="page-footer">
       <div class="right">All Rights Reserved, &copy; 2023 Crave by GA Rejects &nbsp;</div>
    </footer>
</body>
</html>


<script>
    const links = document.querySelectorAll("nav .right a");
    const currentLocation = window.location.pathname;

    links.forEach(link => {
        
        if (link.getAttribute("href") === currentLocation) {
            link.classList.add("active");
        }
    });


</script>

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

{% endblock %}

main_app/templates/main_app/place_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Place</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' place.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/place_form.html
{% extends 'base.html' %}
{% block content %}
<h1>Add Place</h1>

<form action="" method="POST">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDqlpeJtFbNQZVU9IhQJbYW4PIBPaDZuqY&libraries=places"></script>
<script>

    const ratingEl = document.getElementById('id_rating');
    M.FormSelect.init(ratingEl);

    const placeTypeEl = document.getElementById('id_place_type');
    M.FormSelect.init(placeTypeEl);

    const statusEl = document.getElementById('id_status');
    M.FormSelect.init(statusEl);

    const placeNameEl=document.getElementById("id_name");
    const placeLocationEl = document.getElementById("id_location");
    const autocomplete = new google.maps.places.Autocomplete(placeNameEl)
    autocomplete.addListener("place_changed", function(){
        const place=autocomplete.getPlace();
        placeLocationEl.value = place.formatted_address
        placeNameEl.value=place.name
    })
</script>


{% endblock %}

main_app/templates/places/detail.html
{% extends 'base.html' %}
{% block content %}
<div class="card">
      <div class="card-content">
        <span class="card-title">{{ place.name }}</span>
        <p>Location: {{ place.location }}</p>
        <p>Rating: {{ place.rating }}</p>
        <p>Notes: {{ place.notes|linebreaks }}</p>
      </div>
    <!-- Add the following one as well -->
    <div class="card-action">
        <a href="{% url 'places_update' place.id %}">Edit</a>
        <a href="{% url 'places_delete' place.id %}">Delete</a>
      </div>
  </div>
  {% for photo in place.photo_set.all %}
  <img class="responsive-img card-panel" src="{{photo.url}}">
{% empty %}
  <div class="card-panel teal-text center-align">No Photos Uploaded</div>
{% endfor %}

<form action="{% url 'add_photo' place.id %}" enctype="multipart/form-data" method="POST" class="card-panel">
  {% csrf_token %}
  <input type="file" name="photo-file">
  <br><br>
  <button type="submit" class="btn">Upload Photo</button>
</form>
</div>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDqlpeJtFbNQZVU9IhQJbYW4PIBPaDZuqY&libraries=places"></script>
<script>
    //implement Google Maps map view

</script>
{% endblock %}

main_app/templates/places/hitlist.html
{% extends 'base.html' %}
{%block content%}
<h1 id="list-title"><span >@{{user.username}}'s</span> list</h1>

<table>
    <thead>
        <tr class="grey-text">
            <th>place</th>
            <th>location</th>
            <th>my rating</th>
            <th>notes</th>
        </tr>
    </thead>
    <tbody>
        {% for place in places%}
            <tr class="clickable" data-href="{%url 'detail' place.id %}">
                <td>
                    <a id="place-name">{{ place.name }}</a>
                    <br><span class="grey-text">{{place.get_place_type_display}}</span>
                </td>

                <td>{{ place.location }}</td>
                <td>{{ place.get_rating_display }}</td>
                <td>{{ place.notes }}</td>
            </tr>
        
        </tbody>
        {% endfor %}
    </tbody>
</table>
<script>

const clickable=document.querySelectorAll(".clickable");
clickable.forEach(clickable => {
    clickable.addEventListener('click', () =>{
        window.location.href = clickable.getAttribute('data-href');
    });
});

</script>
{% endblock %}

main_app/templates/places/index.html
{% extends 'base.html' %}
{%block content%}
<h1 id="list-title"><span >@{{user.username}}'s</span> list</h1>

<table>
    <thead>
        <tr class="grey-text">
            <th>place</th>
            <th>location</th>
            <th>my rating</th>
            <th>notes</th>
        </tr>
    </thead>
    <tbody>
        {% for place in places%}
            <tr class="clickable" data-href="{%url 'detail' place.id %}">
                <td>
                    <a id="place-name">{{ place.name }}</a>
                    <br><span class="grey-text">{{place.get_place_type_display}}</span>
                </td>

                <td>{{ place.location }}</td>
                <td>{{ place.get_rating_display }}</td>
                <td>{{ place.notes }}</td>
            </tr>
        
        </tbody>
        {% endfor %}
    </tbody>
</table>
<script>

const clickable=document.querySelectorAll(".clickable");
clickable.forEach(clickable => {
    clickable.addEventListener('click', () =>{
        window.location.href = clickable.getAttribute('data-href');
    });
});

</script>
{% endblock %}